version = 1

[[analyzers]]
name = "javascript"
enabled = true

  [analyzers.meta]
  plugins = ["angular"]
  environment = [
    "browser",
    "cypress",
    "jasmine",
    "jest",
    "jquery",
    "mocha"
  ]
